spring.application.name=reservationService

server.port = 8083
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

#PARA LOCAL

spring.datasource.url=jdbc:postgresql://localhost:5432/db_reservation_service
spring.datasource.username=postgres
spring.datasource.password=postgre


#PARA PRODUCCION
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Configuracion Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Configuracion SMS (Twilio)
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}
twilio.country-code=+51

# Configuracion de Codigos de Verificacion
verificacion.codigo.longitud=6
verificacion.codigo.expiracion-minutos=15

# Solo ejecutar en horario de operacion (ej: 11:30 a 23:30)
app.scheduler.reservas.cron=0 0/30 11-23 * * *

# Mantener conexiones vivas aunque no haya actividad
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000