spring.application.name=paymentService

server.port = 8085
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost


#PARA LOCAL

spring.datasource.url=jdbc:postgresql://localhost:5432/db_payment_service
spring.datasource.username=postgres
spring.datasource.password=postgre


#PARA PRODUCCION

#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}



cloudinary.cloud-name=${CLOUDINARY_NAME}
cloudinary.api-key=${CLOUDINARY_KEY_KOROFOODS}
cloudinary.api-secret=${CLOUDINARY_SECRET_KOROFOODS}

#google.vision.api-key=${GOOGLE_VISION_API_KEY}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Logging
logging.level.com.koroFoods.pagoService=DEBUG
logging.level.org.springframework.amqp=DEBUG
