CREATE TABLE TB_ROL(
    ID_ROL SERIAL PRIMARY KEY,
    DESCRIPCION VARCHAR(50) NOT NULL,
    ACTIVO BOOLEAN DEFAULT TRUE

);

CREATE TABLE TB_DISTRITO (
    ID_DISTRITO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL
);


CREATE TABLE TB_USUARIO (
    ID_USUARIO SERIAL PRIMARY KEY,
    NOMBRES VARCHAR(50) NOT NULL,
    APE_PATERNO VARCHAR(50) NOT NULL,
    APE_MATERNO VARCHAR(50) NOT NULL,
    CORREO VARCHAR(100) UNIQUE NOT NULL,
    CLAVE VARCHAR(255) NOT NULL,
    TIPO_DOC CHAR(3) NOT NULL 
	CHECK(TIPO_DOC IN('DNI','PAS','CDX','CMP')),
	--DNI, PASAPORTE, CARNET DE EXTRANJERIA, CARNET MILITAR/POLICIAL
    NRO_DOC VARCHAR(15) UNIQUE NOT NULL,
    IMAGEN VARCHAR(150) NULL,
    DIRECCION VARCHAR(100) NOT NULL,
    TELEFONO CHAR(9) NOT NULL,
    ID_DISTRITO INT NOT NULL,
    ID_ROL INT DEFAULT 4,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ACTIVO BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (ID_DISTRITO) REFERENCES TB_DISTRITO(ID_DISTRITO),
    FOREIGN KEY (ID_ROL) REFERENCES TB_ROL(ID_ROL)
);