spring.application.name=qualificationService

server.port = 8084
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost

#PARA LOCAL
spring.datasource.url=jdbc:postgresql://localhost:5432/DB_QUALIFICATION_SERVICE
spring.datasource.username=postgres
spring.datasource.password=postgre


#PARA PRODUCCION
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Circuit Breaker config
resilience4j.circuitbreaker.instances.userService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.userService.sliding-window-size=5
resilience4j.circuitbreaker.instances.userService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.userService.sliding-window-type=COUNT_BASED

spring.data.redis.host=localhost
spring.data.redis.port=6379