CREATE TABLE TB_TEMATICA (
    ID_TEMATICA SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    ACTIVO BOOLEAN DEFAULT TRUE
);

CREATE TABLE TB_EVENTO (
    ID_EVENTO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,
    ID_TEMATICA INT NOT NULL,

    FECHA_INICIO TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP NOT NULL,

    COSTO_EVENTO DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    IMAGEN VARCHAR(150),
    ACTIVO BOOLEAN DEFAULT TRUE,

    FOREIGN KEY (ID_TEMATICA) REFERENCES TB_TEMATICA(ID_TEMATICA),
    CONSTRAINT CK_EVENTO_FECHAS CHECK (FECHA_FIN > FECHA_INICIO)
);


CREATE TABLE TB_EVENTO_MESA (
    ID_EVENTO_MESA SERIAL PRIMARY KEY,
    ID_EVENTO INT NOT NULL,
    ID_MESA INT NOT NULL,
    FECHA_DESDE TIMESTAMP NOT NULL,
    FECHA_HASTA TIMESTAMP NOT NULL,
    ACTIVO BOOLEAN DEFAULT TRUE,

    FOREIGN KEY (ID_EVENTO) REFERENCES TB_EVENTO (ID_EVENTO),
    CONSTRAINT UQ_EVENTO_MESA UNIQUE(ID_EVENTO, ID_MESA),
    CONSTRAINT CK_EVENTO_MESA_FECHAS CHECK (FECHA_HASTA > FECHA_DESDE)
);
