CREATE TABLE TB_MESA (
    ID_MESA SERIAL PRIMARY KEY,
    NUMERO_MESA INT UNIQUE NOT NULL,
    CAPACIDAD INT NOT NULL,
    ZONA CHAR(2) NOT NULL CHECK (ZONA IN ('Z1','Z2')),
    ESTADO VARCHAR(15) NOT NULL CHECK (ESTADO IN ('LIBRE', 'ASIGNADA', 'OCUPADA')),
    ACTIVO BOOLEAN DEFAULT TRUE
);
