CREATE TABLE TB_PEDIDO (
    ID_PEDIDO SERIAL PRIMARY KEY,
    ID_MESA INT NOT NULL, -- Solo ID (Table Service)
    ID_USUARIO INT NOT NULL, -- Solo ID mesero (User Service)
    ID_RESERVA INT NOT NULL, -- Agregado para validar si la reserva ya tiene un pedido
    FECHA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SUBTOTAL DECIMAL(10,2) DEFAULT 0.00,
    TOTAL DECIMAL(10,2) DEFAULT 0.00,
    ESTADO VARCHAR(15) NOT NULL CHECK (ESTADO IN ('EP','PA','AN')) -- En proceso, pagado, anulado
);

CREATE TABLE TB_DETALLE_PEDIDO (
    ID_DETALLE SERIAL PRIMARY KEY,
    ID_PEDIDO INT NOT NULL,
    ID_PLATO INT NOT NULL,
    ESTADO VARCHAR(3) NOT NULL CHECK(ESTADO IN ('PED','ENT', 'CAN')), -- PEDIDO, ENTREGADO, CANCELADO
    CANTIDAD INT NOT NULL,
    PRECIO_UNITARIO DECIMAL(10,2) NOT NULL,
    SUBTOTAL DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (ID_PEDIDO) REFERENCES TB_PEDIDO (ID_PEDIDO)
);