CREATE TABLE TB_RESERVA (
    ID_RESERVA SERIAL PRIMARY KEY,
    ID_USUARIO INT NULL,
    ID_MESA INT NOT NULL,
    ID_EVENTO INT NULL,
    TIPO_RESERVA VARCHAR(10) NOT NULL CHECK (TIPO_RESERVA IN ('SIMPLE','ESPECIAL')),
    FECHA_RESERVA TIMESTAMP NOT NULL,    
    ESTADO VARCHAR(15) NOT NULL
        CHECK (ESTADO IN ('PENDIENTE','PAGADA','ASISTIDA','CANCELADA','VENCIDA')),
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    OBSERVACIONES VARCHAR(150) NULL,
    CODIGO_VERIFICACION VARCHAR(10) NULL,
    FECHA_EXPIRACION_CODIGO TIMESTAMP NULL,
    VERIFICADO BOOLEAN DEFAULT FALSE 
);