spring.application.name=menuService


server.port = 8087
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost


spring.datasource.url=jdbc:postgresql://localhost:5432/db_menu_service
spring.datasource.username=postgres
spring.datasource.password=postgre


#PARA PRODUCCION
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#Variblaes de entorno para Cloudinary
cloudinary.cloud-name = ${CLOUDINARY_NAME}
cloudinary.api-key = ${CLOUDINARY_KEY_KOROFOODS}
cloudinary.api-secret = ${CLOUDINARY_SECRET_KOROFOODS}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect