CREATE TABLE TB_CALIFICACION (
    ID_CALIFICACION SERIAL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    TIPO_ENTIDAD VARCHAR(10) NOT NULL CHECK (TIPO_ENTIDAD IN ('PLATO','EVENTO')),
    ID_ENTIDAD INT NOT NULL, -- ID del plato o evento
    PUNTUACION INT NOT NULL CHECK (PUNTUACION BETWEEN 1 AND 5),
    COMENTARIO VARCHAR(500) NULL,
    FECHA_REGISTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ESTADO VARCHAR(3) DEFAULT 'ACT' CHECK (ESTADO IN ('ACT','INA','REP')), -- Activa/Inactiva/Reportada
    UNIQUE (ID_USUARIO, TIPO_ENTIDAD, ID_ENTIDAD)
);