spring.application.name=userService

server.port = 8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost



#PARA LOCAL
spring.datasource.url=jdbc:postgresql://localhost:5432/DB_USER_SERVICE
spring.datasource.username=postgres
spring.datasource.password=postgre


#Conexion para MONGO_DB
spring.data.mongodb.uri=mongodb://localhost:27017/DB_MENSAJES

#PARA PRODUCCION
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Variblaes de entorno para GitHub
github.clientId = Ov23liywDIDTbcViyzqf
github.clientSecret = b72153ead5962d8e58b210f59c20e839e0925e1c

#variables de entorno para Google
google.clientId= 1088815984847-tlafi39j1q8m6sppbkl4l9jn1uqvs9q5.apps.googleusercontent.com

#Variblaes de entorno para Cloudinary
cloudinary.name = {CLOUDINARY_NAME}
cloudinary.key = {CLOUDINARY_KEY_KOROFOODS}
cloudinary.secret = {CLOUDINARY_SECRET_KOROFOODS}

# Multipart Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

# Variables para Gemini API
gemini.api.key=1312313
gemini.api.url=https://generativelanguage.googleapis.com/v1beta
gemini.api.model=gemini-2.5-flash

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=600000